const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='daysie.v2';
const moods=[['5','😄','Great'],['4','😊','Good'],['3','😐','Okay'],['2','😕','Meh'],['1','😢','Tough']];
const tags=['Family','Friends','Work','School','Health','Gratitude','Fun','Rest','Win','Worry'];
const prompts=['What made you smile today?','Name one thing you’re grateful for right now.','What’s something kind you did or saw today?','Describe a small win from today.','What would make tomorrow easier?','What is one worry you can set down for now?','Who are you thankful for, and why?','Describe today using three words.','What did you learn today?','How did you take care of yourself today?'];
const quotes=['Small steps every day add up to big journeys. 🌱','Progress, not perfection. 💛','Every sunrise is a fresh page. ☀️','Celebrate the tiny wins. They count too.','You do not have to do it all today — just the next kind thing.'];
let db={user:'friend',onboarded:false,tasks:[],entries:[],streak:0,lastCheck:'',prompt:0};
let selectedMood=null,selectedTags=[],priority='low',repeat='none',editing=null,timer=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const load=()=>{try{Object.assign(db,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{}};
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const day=d=>(d||new Date()).toISOString().slice(0,10);
const esc=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(title,body=''){const t=document.createElement('div');t.className='toast';t.innerHTML=`${title}<small>${body}</small>`;$('#toastHost').append(t);setTimeout(()=>{t.style.opacity=0;t.style.transform='translateY(-8px)';setTimeout(()=>t.remove(),300)},4500)}
function boot(){load();buildPickers();$('#dailyQuote').textContent=quotes[Math.floor(Math.random()*quotes.length)];if(db.onboarded)showApp();else $('#welcome').classList.remove('hidden');}
function showApp(){ $('#welcome').classList.add('hidden'); $('#app,#tabs,#fab').forEach?.(()=>{}); $('#app').classList.remove('hidden');$('#tabs').classList.remove('hidden');$('#fab').classList.remove('hidden'); const h=new Date().getHours();$('#helloText').textContent=`${h<12?'Good morning':h<18?'Good afternoon':'Good evening'}, ${db.user}!`;$('#dateText').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});showNotifyBanner();renderAll();startClock();}
$('#startBtn').onclick=()=>{db.user=$('#nameInput').value.trim()||'friend';db.onboarded=true;save();showApp()};
function go(tab){['today','tasks','journal','insights'].forEach(v=>{$('#'+v+'View').classList.toggle('hidden',v!==tab);$(`[data-tab="${v}"]`)?.classList.toggle('active',v===tab)}); if(tab==='journal')renderEntries(); if(tab==='insights')renderInsights(); scrollTo({top:0,behavior:'smooth'});}
$$('[data-tab]').forEach(b=>b.onclick=()=>go(b.dataset.tab));
function showNotifyBanner(){if(!('Notification'in window))return;$('#notifyBanner').classList.toggle('hidden',Notification.permission==='granted')}
$('#notifyBtn').onclick=async()=>{if(!('Notification'in window))return toast('Notifications unavailable','This browser does not support them.');const p=await Notification.requestPermission();showNotifyBanner();toast(p==='granted'?'🔔 Reminders on!':'No problem','In-app alerts will still show while Daysie is open.')};
function buildPickers(){ $('#moodPicker').innerHTML=moods.map(m=>`<button class="mood" data-mood="${m[0]}"><span>${m[1]}</span>${m[2]}</button>`).join(''); $$('#moodPicker button').forEach(b=>b.onclick=()=>{selectedMood=+b.dataset.mood;$$('#moodPicker button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}); $('#tagPicker').innerHTML=tags.map(t=>`<button class="chip" data-tag="${t}">${t}</button>`).join(''); $$('#tagPicker button').forEach(b=>b.onclick=()=>{b.classList.toggle('on');selectedTags=b.classList.contains('on')?[...selectedTags,b.dataset.tag]:selectedTags.filter(x=>x!==b.dataset.tag)}); $('#promptText').textContent=prompts[db.prompt%prompts.length]; $('#nextPrompt').onclick=()=>{db.prompt=(db.prompt+1)%prompts.length;save();$('#promptText').textContent=prompts[db.prompt]}; $$('#priorityPicker button').forEach(b=>b.onclick=()=>{priority=b.dataset.priority;$$('#priorityPicker button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}); $$('#repeatPicker button').forEach(b=>b.onclick=()=>{repeat=b.dataset.repeat;$$('#repeatPicker button').forEach(x=>x.classList.remove('on'));b.classList.add('on')}); }
function bumpStreak(){const today=day();if(db.lastCheck===today)return;const y=new Date();y.setDate(y.getDate()-1);db.streak=db.lastCheck===day(y)?db.streak+1:1;db.lastCheck=today;save();}
function openTask(task=null){editing=task?.id||null;$('#dialogTitle').textContent=task?'✏️ Edit reminder':'⏰ New reminder';$('#taskTitle').value=task?.title||'';$('#taskNote').value=task?.note||'';priority=task?.priority||'low';repeat=task?.repeat||'none';const due=task?.due?new Date(task.due):new Date(Date.now()+3600000);$('#taskDate').value=day(due);$('#taskTime').value=due.toTimeString().slice(0,5);$$('#priorityPicker button').forEach(b=>b.classList.toggle('on',b.dataset.priority===priority));$$('#repeatPicker button').forEach(b=>b.classList.toggle('on',b.dataset.repeat===repeat));$('#taskDialog').showModal();}
$$('[data-open-task]').forEach(b=>b.onclick=()=>openTask());
$('#taskForm').onsubmit=e=>{e.preventDefault();const title=$('#taskTitle').value.trim();if(!title)return;const due=$('#taskDate').value?new Date($('#taskDate').value+'T'+($('#taskTime').value||'09:00')).getTime():null;const data={title,due,note:$('#taskNote').value.trim(),priority,repeat,notified:false};if(editing)Object.assign(db.tasks.find(t=>t.id===editing),data);else db.tasks.push({id:id(),done:false,created:Date.now(),...data});save();$('#taskDialog').close();renderAll();toast('✅ Reminder saved',due?'Daysie will nudge you on time.':'Added to your someday list.')};
function nextDue(ms,rep){const d=new Date(ms);if(rep==='daily')d.setDate(d.getDate()+1);if(rep==='weekly')d.setDate(d.getDate()+7);if(rep==='monthly')d.setMonth(d.getMonth()+1);return d.getTime()}
function completeTask(t){t.done=!t.done;if(t.done){t.completed=Date.now();bumpStreak();confetti();if(t.repeat&&t.repeat!=='none'&&t.due)db.tasks.push({...t,id:id(),done:false,completed:null,due:nextDue(t.due,t.repeat),notified:false})}save();renderAll()}
function delTask(idv){db.tasks=db.tasks.filter(t=>t.id!==idv);save();renderAll()}
function snooze(t,min=10){t.due=Date.now()+min*60000;t.notified=false;save();renderAll();toast('😴 Snoozed',`Back in ${min} minutes.`)}
function fmt(ms){const d=new Date(ms),n=new Date(),tm=d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});if(day(d)===day(n))return tm;const x=new Date();x.setDate(x.getDate()+1);if(day(d)===day(x))return 'Tomorrow '+tm;return d.toLocaleDateString([],{month:'short',day:'numeric'})+' '+tm}
function taskHTML(t){const late=t.due&&!t.done&&t.due<Date.now();return `<article class="task ${t.priority} ${t.done?'done':''}"><button class="check ${t.done?'on':''}" data-done="${t.id}">${t.done?'✓':''}</button><div class="task-body"><div class="task-title">${esc(t.title)}</div><div class="meta">${t.due?`<span class="${late?'late':''}">${late?'⚠️ ': '🕒 '}${fmt(t.due)}</span>`:''}${t.repeat&&t.repeat!=='none'?`<span>🔁 ${t.repeat}</span>`:''}${t.priority==='high'?'<span>🌸 Important</span>':''}</div>${t.note?`<div class="note">${esc(t.note)}</div>`:''}</div><div class="actions">${late?`<button class="icon" data-snooze="${t.id}">😴</button>`:''}<button class="icon" data-edit="${t.id}">✏️</button><button class="icon" data-delete="${t.id}">🗑️</button></div></article>`}
function renderTasks(){const active=db.tasks.filter(t=>!t.done),done=db.tasks.filter(t=>t.done).sort((a,b)=>(b.completed||0)-(a.completed||0)).slice(0,10);const now=Date.now(),end=new Date();end.setHours(23,59,59,999);const groups=[['⚠️ Overdue',active.filter(t=>t.due&&t.due<now)],['☀️ Today',active.filter(t=>t.due&&t.due>=now&&t.due<=end.getTime())],['📅 Upcoming',active.filter(t=>t.due&&t.due>end.getTime())],['💫 Someday',active.filter(t=>!t.due)],['✅ Recently done',done]];let html='';groups.forEach(([g,arr])=>{arr.sort((a,b)=>(a.due||9e15)-(b.due||9e15));if(arr.length)html+=`<div class="group">${g} · ${arr.length}</div>`+arr.map(taskHTML).join('')});$('#taskList').innerHTML=html||empty('🌼','No reminders yet','Tap + to add one.');const today=groups[1][1].concat(groups[0][1]).sort((a,b)=>(a.due||0)-(b.due||0));$('#todayTasks').innerHTML=today.length?today.map(taskHTML).join(''):empty('✨','Nothing due today','Enjoy your day, or add something new.');bindTaskButtons()}
function bindTaskButtons(){$$('[data-done]').forEach(b=>b.onclick=()=>completeTask(db.tasks.find(t=>t.id===b.dataset.done)));$$('[data-delete]').forEach(b=>b.onclick=()=>delTask(b.dataset.delete));$$('[data-edit]').forEach(b=>b.onclick=()=>openTask(db.tasks.find(t=>t.id===b.dataset.edit)));$$('[data-snooze]').forEach(b=>b.onclick=()=>snooze(db.tasks.find(t=>t.id===b.dataset.snooze)))}
function empty(e,h,s){return `<div class="empty"><div style="font-size:42px">${e}</div><b>${h}</b><p>${s}</p></div>`}
$('#saveEntry').onclick=()=>{const text=$('#journalText').value.trim();if(!text&&!selectedMood)return toast('📝 Add a little something','Pick a mood or write a few words.');db.entries.unshift({id:id(),text,mood:selectedMood,tags:[...new Set(selectedTags)],prompt:prompts[db.prompt],ts:Date.now()});bumpStreak();save();$('#journalText').value='';selectedMood=null;selectedTags=[];$$('#moodPicker button,#tagPicker button').forEach(b=>b.classList.remove('on'));renderAll();confetti();toast('💛 Entry saved','Thanks for checking in today.')};
$('#searchEntries').oninput=renderEntries;
function renderEntries(){const q=$('#searchEntries').value.toLowerCase();const list=db.entries.filter(e=>(e.text||'').toLowerCase().includes(q)||(e.tags||[]).join(' ').toLowerCase().includes(q));$('#entries').innerHTML=list.length?list.map(e=>{const m=moods.find(x=>+x[0]===e.mood);const d=new Date(e.ts);return `<article class="entry"><div class="entry-head"><span class="face">${m?m[1]:'📝'}</span><div><b>${d.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}</b><br><small>${d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}${m?' · '+m[2]:''}</small></div><button class="icon" onclick="deleteEntry('${e.id}')">🗑️</button></div>${e.text?`<p class="entry-text">${esc(e.text)}</p>`:''}<div class="tags">${(e.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div></article>`}).join(''):empty('📖','Your journal awaits','Write your first entry above.')}
window.deleteEntry=x=>{db.entries=db.entries.filter(e=>e.id!==x);save();renderEntries()};
function renderInsights(){const done=db.tasks.filter(t=>t.done).length;$('#stats').innerHTML=[['🔥',db.streak,'Day streak'],['✅',done,'Tasks done'],['📖',db.entries.length,'Entries'],['📋',db.tasks.filter(t=>!t.done).length,'To do']].map(s=>`<div class="stat"><div>${s[0]}</div><b>${s[1]}</b><span>${s[2]}</span></div>`).join('');let days=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);days.push(d)}$('#moodBars').innerHTML=days.map(d=>{let es=db.entries.filter(e=>day(new Date(e.ts))===day(d)&&e.mood),avg=es.length?es.reduce((a,e)=>a+e.mood,0)/es.length:0,m=moods.find(x=>+x[0]===Math.round(avg));return `<div class="bar"><span>${m?m[1]:'·'}</span><i style="height:${avg?avg/5*100:4}%"></i><small>${d.toLocaleDateString([],{weekday:'short'}).slice(0,1)}</small></div>`}).join('');const badges=[['🌱','First step','Add your first reminder',db.tasks.length>=1],['✅','Getting things done','Complete 5 tasks',done>=5],['✍️','Dear diary','Write 3 entries',db.entries.length>=3],['🔥','On a roll','Reach a 3-day streak',db.streak>=3],['🌟','Bright week','Reach a 7-day streak',db.streak>=7]];$('#badges').innerHTML=badges.map(b=>`<div class="badge ${b[3]?'':'locked'}"><b>${b[0]}</b><div><strong>${b[1]}</strong><br><small>${b[2]}</small></div></div>`).join('')}
function renderAll(){renderTasks();renderEntries();renderInsights();$('#streakNum').textContent=db.streak;$('#streakText').textContent=db.lastCheck===day()?'You showed up today — amazing!':'Finish a task or journal to keep it glowing.'}
function startClock(){clearInterval(timer);checkReminders();timer=setInterval(checkReminders,15000)}
function checkReminders(){const now=Date.now();let changed=false;db.tasks.forEach(t=>{if(!t.done&&t.due&&t.due<=now&&!t.notified){t.notified=true;changed=true;notify(t)}});if(changed)save()}
function notify(t){beep();toast('⏰ '+esc(t.title),t.note||'Reminder time!');if('Notification'in window&&Notification.permission==='granted'){new Notification('⏰ '+t.title,{body:t.note||'Reminder time!',tag:t.id,requireInteraction:t.priority==='high'})}}
function beep(){try{let C=window.AudioContext||window.webkitAudioContext,c=new C();[660,880,660].forEach((f,i)=>{let o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.connect(g);g.connect(c.destination);let s=c.currentTime+i*.15;g.gain.setValueAtTime(.001,s);g.gain.exponentialRampToValueAtTime(.15,s+.03);g.gain.exponentialRampToValueAtTime(.001,s+.13);o.start(s);o.stop(s+.14)})}catch{}}
function confetti(){for(let i=0;i<28;i++){let p=document.createElement('i');p.textContent=['🌼','✨','💛','🌿'][i%4];p.style.cssText=`position:fixed;z-index:98;left:${50+Math.random()*20-10}%;top:38%;font-style:normal;font-size:${18+Math.random()*12}px;transition:1s ease;pointer-events:none`;document.body.append(p);requestAnimationFrame(()=>{p.style.transform=`translate(${(Math.random()-.5)*420}px,${120+Math.random()*260}px) rotate(${Math.random()*360}deg)`;p.style.opacity=0});setTimeout(()=>p.remove(),1100)}}
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='daysie-backup-'+day()+'.json';a.click()};
function three(){if(!window.THREE)return;const c=$('#garden'),r=new THREE.WebGLRenderer({canvas:c,alpha:true,antialias:true});r.setPixelRatio(Math.min(devicePixelRatio,2));let scene=new THREE.Scene(),cam=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,100);cam.position.z=18;let g=new THREE.Group();scene.add(g);let colors=[0xffcd57,0xff8c9a,0x7fc989,0x79c8ce,0xad97e8,0xffffff];for(let i=0;i<34;i++){let mesh=new THREE.Mesh(new THREE.SphereGeometry(Math.random()*.55+.18,16,16),new THREE.MeshBasicMaterial({color:colors[i%colors.length],transparent:true,opacity:.45}));mesh.position.set((Math.random()-.5)*34,(Math.random()-.5)*26,(Math.random()-.5)*10);mesh.userData={x:mesh.position.x,y:mesh.position.y,s:Math.random()*.5+.2,p:Math.random()*9};g.add(mesh)}function resize(){r.setSize(innerWidth,innerHeight);cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix()}addEventListener('resize',resize);resize();let t=0;(function loop(){t+=.01;g.children.forEach(m=>{m.position.x=m.userData.x+Math.sin(t*m.userData.s+m.userData.p)*1.2;m.position.y=m.userData.y+Math.cos(t*m.userData.s+m.userData.p)*1.1});g.rotation.y=Math.sin(t*.25)*.08;r.render(scene,cam);requestAnimationFrame(loop)})()}
setTimeout(three,500);boot();